### ISSUE TITLE
Use of Tuple Extraction Obscures Arguments

### ISSUE THREAD

**Issue by zachriggle** [lassimus/grapefruit#1]
It's very hard to tell what the arguments are for a given command, because they're declared like this:

``` py
def enableScript(commands):
    if len(commands) != 2:
        print "incorrect usage. see help"
        return False

    name = commands[1]
```

Instead of being declared in the normal fashion and being invoked with argument expansion

``` py
def enableScript(name, ...):
    ...

enableScript(*list)
```

Alternately, Python2 permits embedded tuples.  This is broken on Python3 and should be discouraged, but works on your target of Python2.

``` py
def enableScript((name, ...)):
    ...

enableScript(1,2,3)
```

**Comment by mattshockl** [comment]
You're completely correct.  This whole script was hacked together in a few hours before a recent ctf and could be improved in a few ways (cleaner code and better thread management mainly).  In the coming weeks, we'll be cleaning up things like this to make it more readable/expandable, and in line with other modern Python platforms

**Comment by mattshockl** [comment]
Spent a few hours and changed this along with reorganizing almost all (98%) of the code.  Thanks for the input, @zachriggle!
